logging:
  group:
    business: dev.allisson.algaposts.text.processor.service
  level:
    business: debug

server:
  port: 8081

spring:
  application:
    name: text-processor-service
  mvc:
    problemdetails:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq